function [ dataDecimate, data, symbolPeriod, samplingPeriod, samplingPeriodDecimate, type, numberOfSymbols ] = readSignal_20171121( fname, nReadr )

%READSIGNALDATA Reads signal data to "visualizer".
%   [ data, samplingFrequency ] = READSIGNALDATA(fid, type, symbolPeriod, samplingPeriod)
%   just reads data ("data") from a file ("fid")
%   knowing the data parameters ("type", "symbolPeriod" and "samplingPeriod") and 
%   returning the new sampling simulation frequency ("samplingFrequency").

%   nReadr specifies the number of symbols to read
%% Global variables related to AWG limitations of sampling rate and waveform memory
maximumSamplingFrequency = 16e9;         % set the maximum sampling rate of the AWG
maximumWaveformMemory    = 8e9;          % set the maximum waveform memory of the AWG

%% Open the "*.sgn" file generated by the simulator and read the content of the file
fid = fopen(fname,'r');                                     % read a particular "*.sgn" signal

type = fscanf(fid,'Signal type: %s\n',1);                   % Extraxt the type of the signal (i.e. type = TimeContinuousAmplitudeContinuousReal)
symbolPeriod = fscanf(fid,'Symbol Period (s): %f\n',1);     % Extract the symbol period of the signal (i.e. symbolPeriod = 2e-10)
samplingPeriod = fscanf(fid,'Sampling Period (s): %f\n',1); % Extract the sampling period of the signal (i.e. samplingPeriod = 1.25e-11). 
%                                                             REMEMBER OUR LIMITATION IS maximumSamplingRate = 6.2500e-11
fscanf(fid,'// ### HEADER TERMINATOR ###\n',1);             % It will just check our header terminator

symbolFrequency   = 1/symbolPeriod;
samplingFrequency = 1/samplingPeriod;
samplingFrequencyDecimate = 1/samplingPeriod;

%% Some Standard types
clc
tb = 'Binary';
tc1 = 'TimeDiscreteAmplitudeDiscreteComplex';
tc2 = 'TimeDiscreteAmplitudeContinuousComplex';
tc3 = 'TimeContinuousAmplitudeDiscreteComplex';
tc4 = 'TimeContinuousAmplitudeContinuousComplex';
tc5 = 'BandpassSignal';
toxy = 'OpticalSignalXY';
% Get global variable "nRead" & set data types
if nargin == 1
    nReadr = Inf;
end
t_binaryr = 'int';
t_realr = 'double';
t_complexr = 'double';
%% Number of samples per period
if (symbolPeriod==1)
    samplesPerSymbol = 1;
else
    samplesPerSymbol = (symbolPeriod/samplingPeriod);
end

%% Read data

% Binary signals
if strcmp(type, tb)
    data = fread(fid, nReadr, t_binaryr);
    data = data';
    
   numberOfSymbols = (length(data)/samplesPerSymbol);
    
    return;
end

% Complex signals
if strcmp(type, tc1) || strcmp(type, tc2) || strcmp(type, tc3) || strcmp(type, tc4) || strcmp(type, tc5)
   data = fread(fid, 2*samplesPerSymbol*nReadr, t_complexr);
   data = data(1:2:end) + 1i.*data(2:2:end);
   data = real(data)' + imag(data)'.*1i;
   numberOfSymbols = (length(data)/samplesPerSymbol);
end

% Complex_xy signals
if strcmp(type, toxy)
   data = fread(fid, 4*double(samplesPerSymbol)*nReadr, t_complexr);
   numberOfSymbols = (length(data)/samplesPerSymbol);
end

% Other signals
data = fread(fid, double(samplesPerSymbol)*nReadr, t_realr);
data = data';

% Number of symbols
numberOfSymbols = (length(data)/samplesPerSymbol);


%% ROMIL
% Display CAUTION if Set samplingPeriod < 6.2500e-11
if (samplingFrequency > maximumSamplingFrequency)
    fprintf('CAUTION !!! sampling frequency must be less than %d \nCurrent sampling frequency is %d %d \n', maximumSamplingFrequency, samplingFrequency);
end

% Reduce the sampling period by a given factor 'r'.
maximumSamples = 0;
if (samplingFrequency < maximumSamplingFrequency)
    samplingFrequencyDecimate = samplingFrequencyDecimate;
else
    while samplingFrequencyDecimate > maximumSamplingFrequency
    samplingFrequencyDecimate = samplingFrequencyDecimate - symbolFrequency;
    maximumSamples = maximumSamples +1;
    end
end

difference = samplesPerSymbol-maximumSamples;
r = ceil(samplesPerSymbol/difference);        % This 'r' is the decimation factor

%% New sampling period
samplingPeriodDecimate = 1/samplingFrequencyDecimate;           
fprintf('\n\nNew "samplingPeriodDecimate = %d" and the decomation factor "r = %d"\n',samplingPeriodDecimate, r);

%% Number of samples per period
if (symbolPeriod==1)
    samplesPerSymbolDecimate = 1;
else
    samplesPerSymbolDecimate = (symbolPeriod/samplingPeriodDecimate);
end

%%
if (r==0)
    dataDecimate = data;
else
    dataDecimate = decimate(data,r);    
end

figure;
t = (0:1:length(data)-1)*samplingPeriod;
tDecimate = (0:r:length(data)-1)*samplingPeriod;
plot(t(1:end),data(1:end),'-o');
grid on
hold on
stem(tDecimate(1:end),dataDecimate(1:end),'ro','filled','markersize',4);
xlabel 'Time in Seconds',ylabel 'Signals'
legend('Original','Decimated')

figure;
plot(tDecimate(1:end),dataDecimate(1:end));
xlabel 'Time in Seconds',ylabel 'Signal'
title('Signal Generated by AWG');
